import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Chatbot iframe */}
        <iframe
          id='myIframe'
          allow='microphone'
          src='https://www.qa-app.exei.ai/sdk/681c98fedd49d14d35176712?mic=true&channelType=IFRAME&API_KEY=426acd05681c48108970c5c22fcf7131'
          style={{
            position: 'fixed',
            bottom: '85px',
            right: '20px',
            width: '400px',
            height: '70%',
            border: 'none',
            zIndex: 9999,
          }}
          title='Exei SDK'
        />
        <Script
          src='https://exei-qa-bucket.s3.us-east-2.amazonaws.com/public/script.js'
          strategy='afterInteractive'
        />

        {children}
      </body>
    </html>
  );
}
