import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <iframe
          id="myIframe"
          allow="microphone"
          src="https://www.qa-app.exei.ai/sdk/68a5736d056b84c0782ac501?mic=true&channelType=WEBSITE&API_KEY=e7597b95ae7b4e05b2407c5127ce49a4"
          title="Exei SDK"
          style={{
            position: "fixed",
            bottom: "85px",
            right: "20px",
            width: "0px",
            height: "0px",
            border: "none",
            zIndex: 9999,
            display: "block",
            background: "transparent",
            borderRadius: "20px",
          }}
        >
          <p>Your browser does not support iframes.</p>
        </iframe>

        <Script
          src='https://iframe-cdn.exei.ai/script-qa-minified.js' 
          strategy='afterInteractive'
        />
        {children}
      </body>
    </html>
  );
}
