import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Chatbot iframe */}
        <iframe
          id='myIframe'
          allow='microphone'
          src='https://www.staging-app.exei.ai/sdk/682325667a186a094810c8c5?mic=true&channelType=IFRAME&API_KEY=f93338c38a914b1cae136e390095a0d8'
          style={{
            position: 'fixed',
            bottom: '85px',
            right: '20px',
            width: '400px',
            height: '70%',
            border: 'none',
            zIndex: 9999,
          }}
          title='Exei SDK'
        >
          <p>Your browser does not support iframes.</p>
        </iframe>
        <Script
          // src='https://exei-bkt-important-object.s3.ap-south-1.amazonaws.com/script-qa-minified.js'
          src='/script.js'
          strategy='afterInteractive'
        />

        {children}
      </body>
    </html>
  );
}
